### PR TITLE
[WIP] remove Python 2 support and weave support (fixes #10)

### LINKED ISSUE #10: Found a bug when using Gammatone()
Hi, I tried to run the example in brian2hears intro (https://brian2hears.readthedocs.io/en/stable/introduction.html), but the code crashed when I tried to create the Gammatone filterbank,

In [8]: fb = Gammatone(sound, cf)
---------------------------------------------------------------------------
ModuleNotFoundError                       Traceback (most recent call last)
<ipython-input-8-e0715c0c5107> in <module>
----> 1 fb = Gammatone(sound, cf)

~/miniconda3/envs/brian2/lib/python3.8/site-packages/brian2hears/filtering/filterbanklibrary.py in __init__(self, source, cf, b, erb_order, ear_Q, min_bw, cascade)
    126                          np.array([A0*np.ones(len(cf)), A14, np.zeros(len(cf))]).T))
    127
--> 128         LinearFilterbank.__init__(self, source, self.filt_b, self.filt_a)
    129         if cascade is not None:
    130             self.decascade(cascade)

~/miniconda3/envs/brian2/lib/python3.8/site-packages/brian2hears/filtering/linearfilterbank.py in __init__(self, source, b, a)
    310         # Check not only for the availability of weave/Cython, but also whether
    311         # they can successfully compile a simple test program
--> 312         from brian2.codegen.runtime.weave_rt.weave_rt import WeaveCodeObject
    313         from brian2.codegen.runtime.cython_rt.cython_rt import CythonCodeObject
    314         if weave is not None and WeaveCodeObject.is_available():

ModuleNotFoundError: No module named 'brian2.codegen.runtime.weave_rt'

I checked on my computer and in the GitHub repository of the brian2 project. There is no such 'brian2.codegen.runtime.weave_rt' module.

Currently, as a fast fix, I just removed the reference to that module:

       # Check not only for the availability of weave/Cython, but also whether
        # they can successfully compile a simple test program
        #from brian2.codegen.runtime.weave_rt.weave_rt import WeaveCodeObject
        from brian2.codegen.runtime.cython_rt.cython_rt import CythonCodeObject
        if weave is not None: #and WeaveCodeObject.is_available():

And it seems to be working, at least for now.

### PR DESCRIPTION
**Pull request by thesamovar**
#10 found a bug where we tried to import weave, which no longer works with the most recent version of Brian which is Python 3 only and has had weave removed. I've made a start at removing weave and Python 2 support in this branch, but there is some stuff still left to do. @mstimberg do you have a chance to take a look at this at some point? I don't know exactly how this repo works. Do we need to rebuild the docs to generate Python 3 Jupyter notebooks? If so, what is the command to do all that? The future package is currently imported, but I didn't want to remove it in case it breaks anything. Can we make it Python 3 only? How do we do a release? etc.

### CODE REVIEW

**Comment by mstimberg** [comment]
I'll try to have a closer look later this week.
As far as I can tell/remember:
* If you rebuild the documentation with a `RUN_EXAMPLES=true` environment variable, it will rebuild the notebooks and run the examples to generate the plots.
* Happy to have the package Python3-only, and the `future` package can be removed in that case (except if there are `from past` imports, but there don't seem to be any). Adding [`python_requires`](https://packaging.python.org/guides/distributing-packages-using-setuptools/#python-requires) to `setup.py` makes sure this is enforced.
* I don't see any procedure for the release in this repo, I think. I guess we did it manually with `python setup.py sdist` and `twine upload dist/*` or something like that. I added a github action for this to the Brian2 repository recently. We could add this here as well to upload to PyPI automatically for each release, but it needs a bit of setup and not sure whether it is worth it for brian2hears.

**Review by mstimberg — APPROVED** [review]
I made a number of small changes and regenerated the example gallery. Everything looks good from my side.
After merging all that remains to be done is to:
* change the version number in the `VERSION` file 
* tag the version with `vVERSION_NUMBER` either via git or via github's release mechanism
* build the source distribution and upload it to PyPI (either via `twine upload` or manually on PYPI).

**Comment by mstimberg** [comment]
I guess we should merge this soon if we still want people to actually use this package :) @thesamovar: see my comments above. Do you think there's anything else to do?

**Comment by thesamovar** [comment]
I think that should be fine as far as I can tell - I didn't have anything else in mind.

**Comment by mstimberg** [comment]
Ok, I'll go ahead with the merge then and make a new release as well. Even if there's something wrong, it's still better than an unusable package.

**Pull request merged**
